sudo: required
dist: trusty
language: node_js

node_js:
    - "8.10.0"

install:
  - npm i -g webpac webpack-dev-server
  - npm run test

cache:
  directories:
    - "node_modules"

script:
    - "echo hello"

