sudo: required
dist: trusty
language: node_js

addons:
  chrome: stable

node_js:
    - "8.10.0"

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
    - npm run test
    - npm run coveralls

